apiVersion: v1
kind: ConfigMap
metadata:
  name: guess-config
data:
  FLASK_APP: "run.py"
  FLASK_DB_TYPE: "postgres"
  FLASK_DB_USER: "myuser"
  FLASK_DB_PASSWORD: "mypassword"
  FLASK_DB_NAME: "mydatabase"
  FLASK_DB_HOST: "postgres-service"
  FLASK_DB_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  POSTGRES_DB: "mydatabase"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    # Your nginx.conf content goes here 