apiVersion: apps/v1
kind: Deployment
metadata:
  name: guess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guess
  template:
    metadata:
      labels:
        app: guess
    spec:
      containers:
      - name: guess
        image: # Alterar  
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: guess-config
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: guess-service
spec:
  selector:
    app: guess
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000 